INSERT INTO hotels (name, location, created_at)
VALUES ('Hotel Azerbaijan', 'Baku', CURRENT_TIMESTAMP),
       ('Hotel Caspian', 'Baku', CURRENT_TIMESTAMP),
       ('Sea View Resort', 'Sumqayit', CURRENT_TIMESTAMP),
       ('Mountain Lodge', 'Gabala', CURRENT_TIMESTAMP),
       ('Grand Palace', 'Baku', CURRENT_TIMESTAMP),
       ('Sunset Inn', 'Shamakhi', CURRENT_TIMESTAMP),
       ('River Side Hotel', 'Lankaran', CURRENT_TIMESTAMP),
       ('Forest Retreat', 'Quba', CURRENT_TIMESTAMP),
       ('City Center Hotel', 'Baku', CURRENT_TIMESTAMP),
       ('Blue Lagoon', 'Nabran', CURRENT_TIMESTAMP),
       ('Golden Sands', 'Absheron', CURRENT_TIMESTAMP),
       ('Crystal Hotel', 'Ganja', CURRENT_TIMESTAMP),
       ('Holiday Inn', 'Baku', CURRENT_TIMESTAMP),
       ('Royal Palace', 'Sheki', CURRENT_TIMESTAMP),
       ('Comfort Stay', 'Shirvan', CURRENT_TIMESTAMP),
       ('Oasis Hotel', 'Baku', CURRENT_TIMESTAMP),
       ('Luxury Suites', 'Nakhchivan', CURRENT_TIMESTAMP),
       ('Skyline Hotel', 'Baku', CURRENT_TIMESTAMP),
       ('Emerald Bay', 'Lankaran', CURRENT_TIMESTAMP),
       ('Silk Road Inn', 'Shaki', CURRENT_TIMESTAMP),
       ('Pearl Plaza', 'Baku', CURRENT_TIMESTAMP),
       ('Sunrise Hotel', 'Gabala', CURRENT_TIMESTAMP),
       ('Caspian Breeze', 'Baku', CURRENT_TIMESTAMP),
       ('Grand Horizon', 'Quba', CURRENT_TIMESTAMP),
       ('Seaside Escape', 'Nabran', CURRENT_TIMESTAMP);
